### ISSUE TITLE
Asks for game info (number of players, etc) twice

### ISSUE THREAD

**Issue by rachelmkim** [CSC207-UofT/course-project-windrunners#25]

**Comment by rachelmkim** [comment]
More specifically, the issue is that currently, information about the game such as playerManager is both in the GameState and in the Game class. The duplicate call for asking how many players there are, etc. happens because playerManager is initialized both in the Game class (where it shouldn't be initialized in my opinion, and shouldn't even exist at all) and in the GameState.

The issue with simply getting rid of the instance attributes in the Game class is that the GamePanel accesses them using getter methods. The getter methods need to be static in order for the GamePanel to use them (I'm not quite sure why this is yet), but the getter methods in GameState are not static, which is why I couldn't just simply perform the replacements.

**Comment by andydabin** [comment]
Fixed by refactoring entire game loop structure
